 channels:
     - defaults
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - pip 
     - pip:
       - pandas==1.1.5
       - tensorflow-cpu==2.5.0
       - imutils==0.5.4
       - plotly==4.14.3
       - scikit_learn==0.24.2
       - torch
       - torchvision==0.9.1
       - retinaface-pytorch==0.0.7
       - wget
       - requests
